services:
  n8n:
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
        reservations:
          cpus: '6.0'
          memory: 6G
    image: n8nio/n8n
    restart: always
    ports:
      - "1000:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8nuser}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8npassword}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-adminpassword}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - n8n-network

  postgres:
    image: postgres:17
    restart: always
    ports:
      - "1001:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-n8nuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8npassword}
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge